# This rule is not used by the project test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sanitize.sanitize.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: sanitizer-admin-role
rules:
- apiGroups:
  - sanitize.sanitize.dev
  resources:
  - sanitizers
  verbs:
  - '*'
- apiGroups:
  - sanitize.sanitize.dev
  resources:
  - sanitizers/status
  verbs:
  - get
