apiVersion: sanitize.sanitize.dev/v1alpha1
kind: Sanitizer
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: sanitizer-sample
spec:
  # TODO(user): Add fields here
  #schedule:
  #lastCleanupTime:
